RecipeBox/Models/Recipe.cs
using System.Collections.Generic;

namespace RecipeBox.Models
{
    public class Recipe
    {
        public Recipe()
        {
            this.JoinEntities = new HashSet<CategoryRecipe>();
        }

        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Ingredient { get; set; }
        public string Instruction { get; set; }
        public virtual ApplicationUser User { get; set; }
        public int Rating { get; set; }

        public virtual ICollection<CategoryRecipe> JoinEntities { get;}
    }
}

RecipeBox/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Controllers
{
  [Authorize]
  public class RecipesController : Controller
  {
    private readonly RecipeBoxContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public RecipesController(UserManager<ApplicationUser> userManager, RecipeBoxContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipes = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).ToList();
      var sortedList = userRecipes.OrderByDescending(recipe => recipe.Rating).ToList();
      return View(sortedList);
      
    }
    [Authorize]
    public ActionResult Create()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe, int CategoryId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      recipe.User = currentUser;
      _db.Recipes.Add(recipe);
      _db.SaveChanges();
      if (CategoryId != 0)
      {
          _db.CategoryRecipe.Add(new CategoryRecipe() { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Details(int id)
    {
      var thisRecipe = _db.Recipes
          .Include(recipe => recipe.JoinEntities)
          .ThenInclude(join => join.Category)
          .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipes => recipes.RecipeId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisRecipe);
    }

     [HttpPost]
    public ActionResult Edit(Recipe recipe, int CategoryId)
    {
      if (CategoryId != 0)
      {
        _db.CategoryRecipe.Add(new CategoryRecipe() { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
      }
      _db.Entry(recipe).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    [Authorize]
    public ActionResult AddCategory(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisRecipe);
    }
    [HttpPost]
    public ActionResult AddCategory(Recipe recipe, int CategoryId)
    {
      if (CategoryId != 0)
      {
        _db.CategoryRecipe.Add(new CategoryRecipe() { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
        _db.SaveChanges();
      } 
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipes => recipes.RecipeId == id);
      return View(thisRecipe);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipes => recipes.RecipeId == id);
      _db.Recipes.Remove(thisRecipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCategory(int joinId)
    {
        var joinEntry = _db.CategoryRecipe.FirstOrDefault(entry => entry.CategoryRecipeId == joinId);
        _db.CategoryRecipe.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Search()
    {
        return View();      
    }

    [HttpPost]
    public ActionResult Search(string searchIngredient)
    {
      var model = _db.Recipes.Where(p => p.Ingredient.ToLower().Contains(searchIngredient.ToLower()));
      return View("Index", model);
    }
  }
}
  

RecipeBox/Views/Recipes/AddCategory.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Add a category</h2>

<h4>Add a category to this task: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RecipeId)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

RecipeBox/Views/Recipes/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.Ingredient)
    @Html.TextBoxFor(model => model.Ingredient)

    @Html.LabelFor(model => model.Instruction)
    @Html.TextBoxFor(model => model.Instruction)

    @Html.Label("Recipe rating 1-10")
    @Html.TextBoxFor(model => model.Rating)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Add new Recipe" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Recipes", "Index")</p>

RecipeBox/Views/Recipes/Delete.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index") 

RecipeBox/Views/Recipes/Details.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Recipe Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Ingredient): @Html.DisplayFor(model => model.Ingredient)</h3>
<h3>@Html.DisplayNameFor(model => model.Instruction): @Html.DisplayFor(model => model.Instruction)</h3>
<h3>@Html.DisplayNameFor(model => model.Rating): @Html.DisplayFor(model => model.Rating)</h3>
@if(@Model.JoinEntities.Count == 0)
{
  <p>This recipe does not belong to any categories</p>
}
else
{
  <h4>Categories the recipe belongs to:</h4>
}
 <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Category.Name</li>
    @using (Html.BeginForm("DeleteCategory", "Recipes"))
    {
      @Html.Hidden("joinId", @join.CategoryRecipeId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Recipe", "Edit", new { id = Model.RecipeId })</p>
<p>@Html.ActionLink("Delete Recipe", "Delete", new { id = Model.RecipeId })</p>

RecipeBox/Views/Recipes/Edit.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Edit</h2>

<h4>Edit this : @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RecipeId)

    @Html.LabelFor(model => model.Ingredient)
    @Html.EditorFor(model => model.Ingredient)

    @Html.LabelFor(model => model.Instruction)
    @Html.EditorFor(model => model.Instruction)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.Label("recipe rating 1-10")
    @Html.EditorFor(model => model.Rating)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Add a Category", "AddCategory", new { id = Model.RecipeId })</p>

<p>@Html.ActionLink("Back to list", "Index")</p>

RecipeBox/Views/Recipes/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;
@model IEnumerable<RecipeBox.Models.Recipe>

<h1>Recipes for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Recipe recipe in Model)
    {
      <li>@Html.ActionLink($"{recipe.Name}", "Details", new { id = recipe.RecipeId })</li>
    }
  </ul>
} 
else
{
  <h3>No recipes have been added yet!</h3>
}

<p>@Html.ActionLink("Add new recipe", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecipeBox/Views/Recipes/Search.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;
@model IEnumerable<RecipeBox.Models.Recipe>


@using (Html.BeginForm())
{

@Html.Label("Search by Ingredient:")
@Html.TextBox("SearchIngredient")
  <input type="submit" value="Search" />
}